name = "annapoorna-website"
main = ".open-next/worker.js"
compatibility_date = "2026-07-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "annapoorna-website"

[[d1_databases]]
binding = "DB"
database_name = "annapoorna-db"
database_id = "a9a8afe1-59f7-4f56-b311-2b9540f1485f"
